// Objective-C API for talking to trulyao.dev/shared Go package.
//   gobind -lang=objc trulyao.dev/shared
//
// File is generated by gobind. Do not edit.

#ifndef __Shared_H__
#define __Shared_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT long SharedDiff(long a, long b);

FOUNDATION_EXPORT long SharedSum(long a, long b);

#endif
